name: "Pentair MQTT Bridge"
version: "0.1.1"
slug: "pentair_mqtt_bridge"
description: "Bridge a Pentair pool pump over MQTT, decode status, and publish control/state topics."
url: "https://github.com/DeFlanko/ha-pool-pump-mqtt-bridge-addon"
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
options:
  broker: ""
  port: 1883
  username: ""
  password: ""
  topic_up: "D4AD20CF144A/up"
  topic_down: "D4AD20CF144A/down"
  parsed_base: "pentair/pump/status"
  cmd_base: "pentair/pump/cmd"
  discovery_base: "homeassistant"
  discovery_prefix: "pentair_pump"
  ctrl_addr: 33
  pump_addr: 96
  low_rpm: 1650
  high_rpm: 3000
  status_poll_interval: 15
  enable_discovery: true
schema:
  broker: str
  port: port
  username: str?
  password: password?
  topic_up: str
  topic_down: str
  parsed_base: str
  cmd_base: str
  discovery_base: str
  discovery_prefix: str
  ctrl_addr: int
  pump_addr: int
  low_rpm: int
  high_rpm: int
  status_poll_interval: int
  enable_discovery: bool
